/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bg.smg.farm.frames;

import bg.smg.farm.model.Animal;
import bg.smg.farm.services.AnimalService;
import bg.smg.farm.services.ImageUpload;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author smgCCFE
 */
public class NewAnimal extends javax.swing.JFrame {
    
    /**
     * Creates new form NewAnimal
     */
    public NewAnimal() {
        initComponents();
        
    }
    private void assignPicture(){
        ImageUpload kachi = new ImageUpload();
        ImageIcon im = kachi.SlozhiSnimka(this, SnimkaLabel);
        SnimkaLabel.setIcon(im);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SnimkaLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IzberiSnimka = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        kilos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(631, 461, 631, 461));
        setMinimumSize(new java.awt.Dimension(529, 340));
        setResizable(false);
        setSize(new java.awt.Dimension(529, 323));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SnimkaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SnimkaLabel.setText("2");
        getContentPane().add(SnimkaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 150, 150));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Моля въведете данни за животното:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 320, 40));

        jLabel4.setText("Снимка:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 120, 20));

        IzberiSnimka.setText("Избери");
        IzberiSnimka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IzberiSnimkaActionPerformed(evt);
            }
        });
        getContentPane().add(IzberiSnimka, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 90, 120, 20));

        jLabel5.setText("Килограми:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 110, 30));

        kilos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kilosActionPerformed(evt);
            }
        });
        getContentPane().add(kilos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 110, -1));

        jLabel6.setText("Име:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 120, 40));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 110, -1));

        jLabel7.setText("Дата на раждане:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 160, 40));

        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 90, -1));

        jToggleButton1.setText("Запази");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IzberiSnimkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IzberiSnimkaActionPerformed
        assignPicture();
    }//GEN-LAST:event_IzberiSnimkaActionPerformed

    private void kilosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kilosActionPerformed
        
    }//GEN-LAST:event_kilosActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        try {
            Animal an = new Animal();
            AnimalService anSer = new AnimalService();
            anSer.setAllAnimals(name.getText(), kilos.getText(), an.getPictureName(), date.getText());
            this.setVisible(false);
               new MainFrame().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(NewAnimal.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IzberiSnimka;
    private javax.swing.JLabel SnimkaLabel;
    private javax.swing.JTextField date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField kilos;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
